### ISSUE TITLE
Deserialize with error line/column

### ISSUE THREAD

**Issue by probablykasper** [dprint/jsonc-parser#33]
I'd really like a way to deserialize into a struct while seeing the line/column of errors when there's an invalid type. 

With `serde_json::from_str` I parse a string directly into a struct:
```rs
let settings_str = fs::read_to_string(&file_path).unwrap();
serde_json::from_str(&settings_str).unwrap()
```

And that shows the line/column:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: boolean `true`, expected struct Example", line: 0, column: 0)', src/settings.rs:32:40

But with `parse_to_serde_value()` & `serde_json::from_value`, you lose that:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: boolean `true`, expected struct Example", line: 0, column: 0)', src/settings.rs:32:40

**Comment by tv42** [comment]
I think you pasted the same output twice, they both show `line: 0, column: 0`.

**Comment by probablykasper** [comment]
Awesome! Thank you
